variables:
  HATCH_INDEX_USER: $PYPI_USERNAME
  HATCH_INDEX_AUTH: $PYPI_PASSWORD
  HATCH_INDEX_REPO: $PYPI_URL
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY

stages:
  - lint
  - test
  - publish


before_script:
  - python -m pip install --upgrade pip
  - python -m pip install hatch

lint:
  stage: lint
  script:
    - pip install pre-commit pyproject-flake8
    - pre-commit install
    - pre-commit run --all-files

.test:
    script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # make sure Gitlab and Github are accessible such that libraires
    # can be installed directly from source
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - ssh-keyscan gitlab.pasqal.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - python -m hatch -v run pytest

test-py3.8:
  extends: ".test"
  image: python:3.8
  stage: test

test-py3.9:
  extends: ".test"
  image: python:3.9
  stage: test

test-py3.10:
  extends: ".test"
  image: python:3.10
  stage: test

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - python -m hatch build
    - python -m hatch publish
